### ISSUE TITLE
Task ensures multipathd is started, and enabled, but should this be systemd?

### ISSUE THREAD

**Issue by Jeter-work** [gluster/gluster-ansible-infra#120]
roles/backend_setup/tasks/blacklist_mpath_devices.yml

```
- name: Ensure that multipathd services is running
  service:
    name: multipathd
    state: started
    enabled: yes
```

Should this be:

```
- name: Ensure that multipathd services is running
  systemd:
    name: multipathd
    state: started
    enabled: yes
```
?

Or is this a case where Ansible is smart and uses service/systemd according to the system?
