### ISSUE TITLE
Add tasks/check_vars.yml for every sub role

### ISSUE THREAD

**Issue by sac** [gluster/gluster-ansible-infra#8]
This tasks file should essential check for the required variables for that particular role.

For example:

```
- name: Checking that required variables are set
  fail: msg="{{ item }} is not defined"
  when: not {{ item }}
  with_items:
    - foo_volname
    - foo_username
    - foo_mastenodes
```

This should essentially do a role sanity check before executing the role.
